### PR TITLE
Update plugin dependencies version to last version 

### PR DESCRIPTION
**Pull request by abdelrahman-abied**

### CODE REVIEW

**Comment by bastulli** [comment]
Please merge, need this

**Comment by kauzige** [comment]
Hello, when this gonna be out?

**Comment by abdelrahman-abied** [comment]
> Hello, when this gonna be out?

use updates from my github it will work

**Comment by app-wizard-arch** [comment]
now package not working in FF 

Error: Failed running flutter pub get...
Because ar_flutter_plugin_flutterflow >=0.7.40 depends on geolocator ^10.0.1 and ar_flutter_plugin_flutterflow <0.7.40 depends on geolocator ^9.0.0, every version of ar_flutter_plugin_flutterflow requires geolocator ^9.0.0 or ^10.0.1.
So, because custom_widget depends on both ar_flutter_plugin_flutterflow any and geolocator 12.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on geolocator: flutter pub add geolocator:^10.1.1

**Comment by hlefe** [comment]
Thank you @abdelrahman-abied for your help, (and sorry for the delayed response) I approve this change and will also add the update to geolocator version 12 on my end in response to @app-wizard-arch

**Pull request merged**
